# Generated by Django 5.2.1 on 2025-05-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='特工名称', max_length=100)),
                ('name_chs', models.CharField(db_comment='特工中文名', max_length=100, null=True)),
                ('img', models.URLField(db_comment='特工图片链接', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='赛事名称', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='地图名称', max_length=100)),
                ('img', models.URLField(db_comment='地图图片链接', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='赛事类型名称', max_length=100, unique=True)),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(db_comment='赛区全称', max_length=50, unique=True)),
                ('abbreviation', models.CharField(db_comment='赛区缩写 (e.g., AMER)', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlr_id', models.CharField(db_comment='来自 vlr.gg 的唯一比赛标识符', max_length=50)),
                ('haojiao_id', models.CharField(db_comment='来自 号角 的唯一比赛标识符', max_length=50)),
                ('vlr_url', models.URLField(db_comment='比赛的 vlr.gg 链接', max_length=255, null=True)),
                ('haojiao_url', models.URLField(db_comment='比赛的 号角 链接', max_length=255, null=True)),
                ('match_data', models.DateTimeField(db_comment='比赛开始时间', null=True)),
                ('team_1_score', models.IntegerField(db_comment='队伍 1 得分', null=True)),
                ('team_2_score', models.IntegerField(db_comment='队伍 2 得分', null=True)),
                ('event_id', models.ForeignKey(db_comment='所属赛事ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.event')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_1_score', models.IntegerField(db_comment='队伍 1 得分', null=True)),
                ('team_2_score', models.IntegerField(db_comment='队伍 2 得分', null=True)),
                ('map_id', models.ForeignKey(db_comment='地图ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.map')),
                ('match_id', models.ForeignKey(db_comment='所属比赛ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.match')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type_id',
            field=models.ForeignKey(db_comment='赛事类型ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.matchtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='region_id',
            field=models.ForeignKey(db_comment='所属赛区ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.region'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='战队名称', max_length=100)),
                ('full_name', models.CharField(db_comment='战队全称', max_length=255, null=True)),
                ('region_id', models.ForeignKey(db_comment='所属赛区ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.region')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='选手名称', max_length=100)),
                ('full_name', models.CharField(db_comment='选手全称', max_length=255, null=True)),
                ('nation', models.CharField(db_comment='选手国籍', max_length=100, null=True)),
                ('img', models.URLField(db_comment='选手图片链接', max_length=255, null=True)),
                ('team_id', models.ForeignKey(db_comment='目前所属队伍ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(db_comment='选手Rating', null=True)),
                ('acs', models.IntegerField(db_comment='选手ACS', null=True)),
                ('KDA_K', models.IntegerField(db_comment='Kills', null=True)),
                ('KDA_D', models.IntegerField(db_comment='Deaths', null=True)),
                ('KDA_A', models.IntegerField(db_comment='Assists', null=True)),
                ('KD_diff', models.IntegerField(db_comment='KDA差值', null=True)),
                ('kast', models.FloatField(db_comment='KAST', null=True)),
                ('adr', models.FloatField(db_comment='ADR', null=True)),
                ('headshot', models.FloatField(db_comment='HS%', null=True)),
                ('first_kill', models.IntegerField(db_comment='首杀数', null=True)),
                ('first_death', models.IntegerField(db_comment='首死数', null=True)),
                ('first_kill_diff', models.IntegerField(db_comment='FK-FD差值', null=True)),
                ('agent_id', models.ForeignKey(db_comment='使用的特工ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.agent')),
                ('match_detail_id', models.ForeignKey(db_comment='所属比赛详情ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.matchdetail')),
                ('player_id', models.ForeignKey(db_comment='选手ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.player')),
                ('team_id', models.ForeignKey(db_comment='所属队伍ID', on_delete=django.db.models.deletion.CASCADE, to='match_data.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_id',
            field=models.ForeignKey(db_comment='队伍 1 ID', on_delete=django.db.models.deletion.CASCADE, related_name='team_1_matches', to='match_data.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_id',
            field=models.ForeignKey(db_comment='队伍 2 ID', on_delete=django.db.models.deletion.CASCADE, related_name='team_2_matches', to='match_data.team'),
        ),
    ]
